name: PR Deploy static content to Pages

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job for pull requests
  deploy-pr:
    if: github.event_name == 'pull_request'
    environment:
      name: pr-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Determine PR Branch
        id: pr-branch
        run: echo ::set-output name=branch::${GITHUB_REF/refs\/pull\//}
      - name: Deploy to GitHub Pages
        id: pr-deployment
        uses: actions/deploy-pages@v1
