---
name: Deploy static content to Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy-main:
    environment:
      name: main-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-dist
          path: ./dist
      - name: Deploy to GitHub Pages
        id: main-deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact: main-dist
  deploy-pr:
    environment:
      name: pr-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-dist
          path: ./dist
      - name: Determine PR Branch
        id: pr-branch
        run: echo ::set-output name=branch::${GITHUB_REF/refs\/pull\//}
      - name: Deploy to GitHub Pages
        id: pr-deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact: pr-dist
          target_branch: ${{ steps.pr-branch.outputs.branch }}
